# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CdnxxNJ4sg4D7O2-iZadeKwa44Q23AY2
"""

import zipfile

zip_file_path = '/content/archive (6).zip'

with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    zip_ref.extractall('.')

print(f"Contents of {zip_file_path} extracted successfully.")

import pandas as pd

df = pd.read_csv('budget_data.csv')
print("DataFrame 'df' loaded successfully.")
print("First 5 rows of df:")
print(df.head())

category_mapping = {
    'Restuarant': 'Food & Dining',
    'Coffe': 'Food & Dining',
    'Business lunch': 'Food & Dining',
    'Market': 'Food & Dining',
    'Transport': 'Transportation',
    'Taxi': 'Transportation',
    'Rent Car': 'Transportation',
    'Fuel': 'Transportation',
    'Clothing': 'Personal Care & Lifestyle',
    'Sport': 'Personal Care & Lifestyle',
    'Health': 'Personal Care & Lifestyle',
    'Film/enjoyment': 'Personal Care & Lifestyle',
    'joy': 'Personal Care & Lifestyle',
    'Phone': 'Utilities & Services',
    'Communal': 'Utilities & Services',
    'Motel': 'Travel & Accommodation',
    'Travel': 'Travel & Accommodation',
    'Learning': 'Business & Professional',
    'Tech': 'Business & Professional',
    'business_expenses': 'Business & Professional',
    'Other': 'Miscellaneous',
    'Events': 'Miscellaneous'
}

df['broad_category'] = df['category'].map(category_mapping)

print("First 5 rows of df with new 'broad_category' column:")
print(df.head())
print("\nValue counts for 'broad_category':")
print(df['broad_category'].value_counts())

df['date'] = pd.to_datetime(df['date'])

df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['day_of_week'] = df['date'].dt.dayofweek # Monday=0, Sunday=6
df['is_weekend'] = df['day_of_week'].isin([5, 6])

print("First 5 rows of df with new date features:")
print(df.head())

y = df['broad_category']
X = df.drop(columns=['date', 'category', 'broad_category'])

print("Shape of features (X):", X.shape)
print("Shape of target (y):", y.shape)
print("First 5 rows of features (X):")
print(X.head())

X_encoded = pd.get_dummies(X, columns=['is_weekend', 'day_of_week', 'month', 'year'], drop_first=True)

print("Shape of encoded features (X_encoded):", X_encoded.shape)
print("First 5 rows of encoded features (X_encoded):")
print(X_encoded.head())

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_encoded, y, test_size=0.2, random_state=42, stratify=y)

print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

# 1. Initialize and train a LogisticRegression model
model = LogisticRegression(max_iter=1000, random_state=42)
model.fit(X_train, y_train)
print("Logistic Regression model trained successfully.")

# 2. Make predictions on the X_test dataset
y_pred = model.predict(X_test)
print("Predictions made on the test set.")

# 3. Calculate and print the accuracy of the model on the test set
accuracy = accuracy_score(y_test, y_pred)
print(f"\nModel Accuracy: {accuracy:.4f}")

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import StandardScaler

# Scale the data to address convergence warning
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# 1. Initialize and train a LogisticRegression model
# Use scaled data for training
model = LogisticRegression(max_iter=1000, random_state=42)
model.fit(X_train_scaled, y_train)
print("Logistic Regression model trained successfully with scaled data.")

# 2. Make predictions on the scaled X_test dataset
y_pred = model.predict(X_test_scaled)
print("Predictions made on the test set.")

# 3. Calculate and print the accuracy of the model on the test set
accuracy = accuracy_score(y_test, y_pred)
print(f"\nModel Accuracy (with scaled data): {accuracy:.4f}")

from sklearn.metrics import classification_report

# 4. Print a classification_report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

from sklearn.metrics import ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# 5. Generate and plot a confusion matrix
fig, ax = plt.subplots(figsize=(10, 8))
ConfusionMatrixDisplay.from_estimator(model, X_test_scaled, y_test, ax=ax, cmap=plt.cm.Blues, xticks_rotation='vertical')
plt.title('Confusion Matrix for Broad Category Prediction')
plt.show()

from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# 1. Initialize and train a Gaussian Naive Bayes model
naive_bayes_model = GaussianNB()
naive_bayes_model.fit(X_train_scaled, y_train)
print("Gaussian Naive Bayes model trained successfully with scaled data.")

# 2. Make predictions on the scaled X_test dataset
y_pred_nb = naive_bayes_model.predict(X_test_scaled)
print("Predictions made on the test set using Naive Bayes.")

# 3. Calculate and print the accuracy of the Naive Bayes model on the test set
accuracy_nb = accuracy_score(y_test, y_pred_nb)
print(f"\nNaive Bayes Model Accuracy (with scaled data): {accuracy_nb:.4f}")

# 4. Print a classification_report for Naive Bayes
print("\nClassification Report for Naive Bayes:")
print(classification_report(y_test, y_pred_nb))

# 5. Generate and plot a confusion matrix for Naive Bayes
fig_nb, ax_nb = plt.subplots(figsize=(10, 8))
ConfusionMatrixDisplay.from_estimator(naive_bayes_model, X_test_scaled, y_test, ax=ax_nb, cmap=plt.cm.Blues, xticks_rotation='vertical')
plt.title('Confusion Matrix for Naive Bayes Broad Category Prediction')
plt.show()